# BASE SERVER SETTINGS (USER DEFINED)
# --------------------------------------------------------------------------
# Do not edit this file!!! It's used ONLY as a template to create the `settings.coffee`
# file in case it is not present on the file system when the app is installed.
# If you want to edit settings, edit the generated `settings.coffee` file directly.

class Settings

# Singleton implementation
# --------------------------------------------------------------------------
Settings.getInstance = ->
    if not @instance?
        xtend = (source, target) ->
            for prop, value of source
                if value?.constructor is Object
                    target[prop] = {} if not target[prop]?
                    xtend source[prop], target[prop]
                else
                    target[prop] = source[prop] if not target[prop]?

        @instance = new Settings()
        settingsDefault = require "./settings.default.coffee"
        xtend settingsDefault, @instance

    return @instance

module.exports = exports = Settings.getInstance()